# Site settings
title: HS
email: t.maxim@gmail.com
description: Site for Hairssime
baseurl: ""
url: "http://hairssime.com.ar"
twitter_username: mixam
github_username:  tmaxim

# Build settings
markdown: kramdown

exclude: [
  'node_modules',
  'bower.json',
  'gulpfile.js',
  'npm-debug.log',
  'package.json',
  'README.md',
  'Gemfile',
  'Gemfile.lock',
  '_productos/*/images/*.png'
]

keep_files: [
  'dist',
  'productos/*/*'
]

permalink: /blog/:year/:month/:day/:title/

collections:
  productos:
    output: true
    title: Productos
    permalink: /productos/:title/
